default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: erro-chat-space_development

test:
  <<: *default
  database: erro-chat-space_test

production:
  <<: *default
  database: erro-chat-space_production
